#!/bin/sh

. packages/audo/meta

rm -rf target/$PKG_VERSION.$PKG_REV/

mkdir build

cp -rf script.module.audo build/script.module.audo

mkdir -p target/$PKG_VERSION.$PKG_REV/
cd build
zip -rq9 ../target/$PKG_VERSION.$PKG_REV/$PKG_NAME-$PKG_VERSION.$PKG_REV.zip script.module.audo
cp script.module.audo/changelog.txt ../target/$PKG_VERSION.$PKG_REV/changelog-$PKG_VERSION.$PKG_REV.txt
cp script.module.audo/addon.xml ../target/$PKG_VERSION.$PKG_REV/addon.xml
cd ..
rm -rf build
